# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_squashed_0003_auto_20160926_1636'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aboutcontent',
            table='website_content_about',
        ),
        migrations.AlterModelTable(
            name='benefit',
            table='website_benefits',
        ),
        migrations.AlterModelTable(
            name='benefitscontent',
            table='website_content_benefits',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='website_contacts',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='website_employees',
        ),
        migrations.AlterModelTable(
            name='getintouchcontent',
            table='website_content_get_in_touch',
        ),
        migrations.AlterModelTable(
            name='introcontent',
            table='website_content_intro',
        ),
        migrations.AlterModelTable(
            name='number',
            table='website_numbers',
        ),
        migrations.AlterModelTable(
            name='service',
            table='website_services',
        ),
        migrations.AlterModelTable(
            name='servicelist',
            table='website_services_lists',
        ),
        migrations.AlterModelTable(
            name='servicelistitem',
            table='website_services_lists_items',
        ),
        migrations.AlterModelTable(
            name='servicescontent',
            table='website_content_services',
        ),
        migrations.AlterModelTable(
            name='teamcontent',
            table='website_content_team',
        ),
    ]
