# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160926_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutcontent',
            options={'verbose_name': 'Блок "Компанія"', 'verbose_name_plural': '          Блок "Компанія"'},
        ),
        migrations.AlterModelOptions(
            name='benefit',
            options={'verbose_name': 'Перевага', 'verbose_name_plural': '    Переваги'},
        ),
        migrations.AlterModelOptions(
            name='benefitscontent',
            options={'verbose_name': 'Блок "Переваги"', 'verbose_name_plural': '         Блок "Переваги"'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': '   Контакти'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Співробітник', 'verbose_name_plural': '  Співробітники'},
        ),
        migrations.AlterModelOptions(
            name='getintouchcontent',
            options={'verbose_name': 'Блок "Звʼязок"', 'verbose_name_plural': '      Блок "Звʼязок"'},
        ),
        migrations.AlterModelOptions(
            name='introcontent',
            options={'verbose_name': 'Блок "Вступ"', 'verbose_name_plural': '           Блок "Вступ"'},
        ),
        migrations.AlterModelOptions(
            name='number',
            options={'verbose_name': 'Цифра', 'verbose_name_plural': '     Цифри'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Сервіс', 'verbose_name_plural': ' Сервіси'},
        ),
        migrations.AlterModelOptions(
            name='servicescontent',
            options={'verbose_name': 'Блок "Сервіси"', 'verbose_name_plural': '        Блок "Сервіси"'},
        ),
        migrations.AlterModelOptions(
            name='teamcontent',
            options={'verbose_name': 'Блок "Команда"', 'verbose_name_plural': '       Блок "Команда"'},
        ),
        migrations.RenameField(
            model_name='servicelistitem',
            old_name='text_uk',
            new_name='text',
        ),
    ]
