# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20161010_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description_uk',
            field=models.CharField(max_length=500, null=True, verbose_name='Короткий опис'),
        ),
    ]
