# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160926_1521'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aboutcontent',
            table='content_about',
        ),
        migrations.AlterModelTable(
            name='benefit',
            table='benefits',
        ),
        migrations.AlterModelTable(
            name='benefitscontent',
            table='content_benefits',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='contacts',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employees',
        ),
        migrations.AlterModelTable(
            name='getintouchcontent',
            table='content_get_in_touch',
        ),
        migrations.AlterModelTable(
            name='introcontent',
            table='content_intro',
        ),
        migrations.AlterModelTable(
            name='number',
            table='numbers',
        ),
        migrations.AlterModelTable(
            name='service',
            table='services',
        ),
        migrations.AlterModelTable(
            name='servicelist',
            table='services_lists',
        ),
        migrations.AlterModelTable(
            name='servicelistitem',
            table='services_lists_items',
        ),
        migrations.AlterModelTable(
            name='servicescontent',
            table='content_services',
        ),
        migrations.AlterModelTable(
            name='teamcontent',
            table='content_team',
        ),
    ]
