# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20161010_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_main_thumb',
            field=models.ImageField(null=True, upload_to='service/images/main/thumb/', verbose_name='Головне зображення'),
        ),
    ]
