# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_service_image_main_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image_main_thumb',
            field=models.ImageField(null=True, upload_to='service/images/main/thumb/', verbose_name='Мініатюра головного зображення'),
        ),
    ]
