# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20161010_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address_uk',
        ),
        migrations.AddField(
            model_name='contact',
            name='address_legal_uk',
            field=models.CharField(default='-', max_length=300, verbose_name='Юридична адреса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='address_post_uk',
            field=models.CharField(default='-', max_length=300, verbose_name='Адреса для листування'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
