# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 15:43
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20161010_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=stdimage.models.StdImageField(upload_to='employee/photos/', verbose_name='Фотографія'),
        ),
    ]
