# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadata',
            options={'verbose_name': 'Метаданные', 'verbose_name_plural': 'Метадані'},
        ),
        migrations.AlterField(
            model_name='metadata',
            name='description_uk',
            field=models.CharField(max_length=250, verbose_name='Опис сторінки'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='robots',
            field=models.CharField(max_length=100, verbose_name='Інформація для ботів'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='title_uk',
            field=models.CharField(max_length=100, verbose_name='Назва сторінки'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='url_name',
            field=models.CharField(max_length=100, verbose_name='Роутінг'),
        ),
    ]
